builds:
- goarch: [amd64, arm, arm64, 386]
  goarm: [6, 7]
  goos: [linux,darwin,windows]
  ignore:
  - goos: darwin
    goarch: 386
  env:
  - CGO_ENABLED=0
  main: ./main.go
  binary: fox
  ldflags:
   - -s -w -X "main.Version={{ .Env.TAG }}" -X "main.Build={{ .Env.BUILD }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
